import Link from "next/link";
import { ArrowRight, Lightbulb, MessageCircleMore, Quote } from "lucide-react";

import { EmbeddedIdeaTranslator } from "@/components/public/embedded-idea-translator";
import type { IdeaBlock } from "@/lib/growth/ideas/contracts";

interface TranslatorRef { id: string; slug: string; name: string; shortDescription: string }

export function IdeaBlocks({ blocks, translators }: { blocks: IdeaBlock[]; translators: TranslatorRef[] }) {
  const byId = new Map(translators.map((item) => [item.id, item]));
  return <div className="min-w-0 space-y-8">{blocks.map((block, index) => {
    if (block.type === "INTRO") return <p key={index} className="font-display border-l-4 border-brand-400 pl-5 text-xl font-bold leading-8 text-ink sm:text-2xl sm:leading-9">{block.text}</p>;
    if (block.type === "PARAGRAPH") return <p key={index} className="text-base leading-8 text-muted-ink sm:text-[1.05rem]">{block.text}</p>;
    if (block.type === "HEADING") return block.level === 2 ? <h2 key={index} className="font-display border-t border-dashed border-border pt-10 text-3xl font-bold leading-tight tracking-tight text-ink sm:text-4xl">{block.text}</h2> : <h3 key={index} className="font-display pt-3 text-2xl font-bold leading-tight text-ink">{block.text}</h3>;
    if (block.type === "IDEA_LIST") return <ol key={index} className="relative space-y-0 border-y border-ink/15">{block.items.map((item, itemIndex) => <li key={itemIndex} className="group grid gap-3 border-b border-dashed border-border py-6 last:border-b-0 sm:grid-cols-[3.5rem_1fr] sm:gap-5 sm:py-7"><span className="font-display text-4xl font-bold leading-none text-brand-500/55 transition group-hover:text-brand-600" aria-hidden="true">{String(itemIndex + 1).padStart(2, "0")}</span><div><p className="font-display text-xl font-bold leading-7 text-ink sm:text-2xl sm:leading-8">{item.text}</p>{item.context ? <p className="mt-2 text-sm leading-6 text-muted-ink">{item.context}</p> : null}{item.note ? <p className="mt-3 border-l-2 border-accent-300 pl-3 text-sm italic leading-6 text-muted-ink">{item.note}</p> : null}</div></li>)}</ol>;
    if (block.type === "EXAMPLE_LIST") return <div key={index} className="space-y-4">{block.items.map((item, itemIndex) => <article key={itemIndex} className="relative overflow-hidden rounded-[1.4rem] border border-brand-200 bg-brand-50 p-5 sm:p-6"><Quote className="absolute right-4 top-4 h-9 w-9 text-brand-300" aria-hidden="true" />{item.original ? <p className="max-w-[85%] text-sm leading-6 text-muted-ink"><span className="font-extrabold uppercase tracking-wide text-brand-800">Instead of</span><br />{item.original}</p> : null}<div className={item.original ? "mt-5 border-t border-brand-200 pt-5" : ""}><p className="font-display text-xl font-bold leading-7 text-ink">{item.suggestion}</p>{item.explanation ? <p className="mt-2 text-sm leading-6 text-muted-ink">{item.explanation}</p> : null}</div></article>)}</div>;
    if (block.type === "TIP_LIST") return <section key={index} className="relative overflow-hidden rounded-[1.6rem] bg-[#fff0c7] p-5 sm:p-7"><div className="mb-4 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/65 text-[#9a5b00]"><Lightbulb className="h-5 w-5" aria-hidden="true" /></span><p className="font-display text-xl font-bold text-ink">A few small moves</p></div><ul className="space-y-3">{block.items.map((item, itemIndex) => <li key={itemIndex} className="flex gap-3 leading-7 text-ink/80"><span aria-hidden="true" className="font-bold text-accent-600">{itemIndex + 1}.</span><span>{item}</span></li>)}</ul></section>;
    if (block.type === "CALLOUT") return <aside key={index} className="relative border-y border-dashed border-border py-7 pl-14"><MessageCircleMore className="absolute left-0 top-7 h-8 w-8 text-accent-500" aria-hidden="true" />{block.heading ? <h3 className="font-display text-2xl font-bold text-ink">{block.heading}</h3> : null}<p className="mt-2 leading-7 text-muted-ink">{block.text}</p></aside>;
    const translator = byId.get(block.translatorId);
    if (!translator) return null;
    if (block.type === "TRANSLATOR_CTA") return <aside key={index} className="relative overflow-hidden rounded-[1.75rem] bg-ink p-6 text-white sm:p-8"><span className="absolute -right-8 -top-8 h-32 w-32 rotate-12 rounded-[2rem] bg-brand-400/20" aria-hidden="true" /><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-brand-300">Keep the thought, change the voice</p><h2 className="font-display mt-2 max-w-xl text-3xl font-bold leading-tight">{block.heading}</h2><p className="mt-3 max-w-2xl leading-7 text-white/70">{block.body}</p><Link href={`/translators/${translator.slug}`} className="relative mt-6 inline-flex min-h-11 items-center gap-2 rounded-full bg-brand-400 px-5 py-3 text-sm font-bold text-ink transition hover:bg-brand-300">{block.buttonLabel}<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></aside>;
    return <EmbeddedIdeaTranslator key={index} slug={translator.slug} name={translator.name} heading={block.heading} helperText={block.helperText} />;
  })}</div>;
}
