ALTER TYPE "TranslatorEditorialJobType" ADD VALUE IF NOT EXISTS 'REGENERATE_WHAT_IT_DOES';
ALTER TYPE "TranslatorEditorialJobType" ADD VALUE IF NOT EXISTS 'REGENERATE_DIFFERENCE';
ALTER TYPE "TranslatorEditorialJobType" ADD VALUE IF NOT EXISTS 'REGENERATE_BEST_USES';
ALTER TYPE "TranslatorEditorialJobType" ADD VALUE IF NOT EXISTS 'REGENERATE_HOW_TO_USE';
