import Link from "next/link";
import { ArrowLeft, ChevronDown, ExternalLink, Lightbulb } from "lucide-react";

import { AdminTopbar } from "@/components/admin/admin-topbar";
import { IdeaVersionActions, QueueIdeaDecisionButton } from "@/components/admin/idea-autopilot-actions";
import { getAdminIdeasOverview } from "@/lib/data/ideas";
import { requireAdmin } from "@/lib/permissions";

export const dynamic = "force-dynamic";

function humanize(value: string) {
  return value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase());
}

function statusClass(status: string) {
  if (["PUBLISHED", "COMPLETED", "ACTIONED"].includes(status)) return "bg-brand-100 text-brand-900";
  if (["WAITING_DATA", "DEFERRED", "DRAFT", "PROPOSED"].includes(status)) return "bg-[#fff0c7] text-[#805000]";
  if (["FAILED_TERMINAL", "REJECTED", "CANCELLED", "ARCHIVED"].includes(status)) return "bg-red-50 text-red-800";
  return "bg-supporting-100 text-supporting-900";
}

export default async function AdminGrowthIdeasPage() {
  await requireAdmin();
  const overview = await getAdminIdeasOverview();
  const published = overview.ideas.filter((idea) => idea.status === "PUBLISHED").length;
  const activeCategories = overview.categories.filter((category) => category.isActive && !category.archivedAt).length;

  return <>
    <AdminTopbar title="SayTwist Ideas" subtitle="Plan, review, and manage useful editorial content built from Growth evidence." />
    <main className="space-y-10 p-4 sm:p-6 lg:p-8">
      <div className="flex flex-wrap items-center justify-between gap-4"><Link href="/admin/growth" className="inline-flex items-center gap-2 text-sm font-bold text-muted-ink transition hover:text-brand-700"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Growth overview</Link><p className="rounded-full bg-brand-100 px-4 py-2 text-xs font-bold text-brand-900">One-shot jobs · immutable versions</p></div>

      <section aria-label="Ideas status" className="grid overflow-hidden rounded-2xl border border-border bg-white sm:grid-cols-2 xl:grid-cols-4">
        {[{ label: "Published Ideas", value: published, note: `${overview.ideas.length} recent total` }, { label: "Open opportunities", value: overview.opportunities.length, note: "Eligible for a decision" }, { label: "Recent decisions", value: overview.decisions.length, note: "Latest audit outcomes" }, { label: "Active categories", value: activeCategories, note: `${overview.categories.length} taxonomy entries` }].map((metric, index) => <div key={metric.label} className={`p-4 sm:p-5 ${index ? "border-t border-border sm:border-l sm:border-t-0" : ""}`}><p className="text-[11px] font-extrabold uppercase tracking-[0.12em] text-muted-ink">{metric.label}</p><p className="font-display mt-1 text-3xl font-bold text-ink">{metric.value}</p><p className="mt-1 text-xs text-muted-ink">{metric.note}</p></div>)}
      </section>

      <section aria-labelledby="idea-opportunities-heading" className="overflow-hidden rounded-[1.75rem] border border-brand-200 bg-brand-50/65">
        <div className="flex flex-wrap items-end justify-between gap-4 border-b border-brand-200 p-5 sm:p-6"><div><p className="section-kicker">Action area</p><h2 id="idea-opportunities-heading" className="font-display mt-1 text-3xl font-bold text-ink">Eligible opportunities</h2><p className="mt-1 text-sm text-muted-ink">Evidence that may be ready for an Idea planning decision.</p></div><span className="text-sm font-bold text-brand-800">{overview.opportunities.length} open</span></div>
        {overview.opportunities.length ? <div className="divide-y divide-brand-200">{overview.opportunities.map((item) => <article key={item.id} className="grid gap-4 bg-white/55 p-5 sm:grid-cols-[1fr_auto] sm:items-center sm:p-6"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-white px-2.5 py-1 text-xs font-bold text-brand-800">{humanize(item.type)}</span><span className="text-xs font-bold text-muted-ink">Evidence: {humanize(item.evidenceQuality)}</span></div><h3 className="font-display mt-2 text-xl font-bold text-ink">{item.cluster?.name || "Unclustered opportunity"}</h3><div className="mt-3 flex flex-wrap gap-5"><div><p className="text-[10px] font-extrabold uppercase tracking-wider text-muted-ink">Score</p><p className="font-display text-2xl font-bold text-ink">{item.score}</p></div><div><p className="text-[10px] font-extrabold uppercase tracking-wider text-muted-ink">Confidence</p><p className="font-display text-2xl font-bold text-ink">{item.confidence}%</p></div></div></div><QueueIdeaDecisionButton opportunityId={item.id} /></article>)}</div> : <div className="flex min-h-40 flex-col items-center justify-center p-8 text-center"><Lightbulb className="h-6 w-6 text-brand-700" aria-hidden="true" /><h3 className="font-display mt-3 text-xl font-bold text-ink">No open opportunities</h3><p className="mt-1 text-sm text-muted-ink">New evidence-backed opportunities will appear here.</p></div>}
      </section>

      <section aria-labelledby="recent-ideas-heading">
        <div className="border-b border-dashed border-border pb-5"><p className="section-kicker">Content library</p><h2 id="recent-ideas-heading" className="font-display mt-1 text-3xl font-bold text-ink">Recent Ideas</h2><p className="mt-1 text-sm text-muted-ink">Review the content first; version provenance remains one click away.</p></div>
        {overview.ideas.length ? <div className="mt-6 grid gap-5 xl:grid-cols-2">{overview.ideas.map((idea) => {
          const references = idea.currentVersion?.translatorReferences || [];
          return <article key={idea.id} className="flex flex-col overflow-hidden rounded-[1.5rem] border border-border bg-white shadow-[0_18px_50px_-42px_rgba(15,23,42,0.5)]">
            <div className="h-1.5 bg-brand-500" aria-hidden="true" />
            <div className="flex flex-1 flex-col p-5 sm:p-6"><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-brand-50 px-2.5 py-1 text-xs font-extrabold text-brand-800">{idea.category.name}</span><span className={`rounded-lg px-2.5 py-1 text-xs font-extrabold ${statusClass(idea.status)}`}>{humanize(idea.status)}</span><span className="text-xs font-bold text-muted-ink">Version {idea.currentVersion?.version || 0}</span></div><h3 className="font-display mt-3 text-2xl font-bold leading-tight text-ink">{idea.currentVersion?.title || idea.slug}</h3>{idea.currentVersion?.excerpt ? <p className="mt-2 line-clamp-3 text-sm leading-6 text-muted-ink">{idea.currentVersion.excerpt}</p> : null}
              <dl className="mt-5 grid gap-3 border-y border-dashed border-border py-4 text-sm sm:grid-cols-2"><div><dt className="text-xs font-bold text-muted-ink">Published</dt><dd className="mt-0.5 font-semibold text-ink">{idea.publishedAt?.toLocaleDateString() || "Not published"}</dd></div><div><dt className="text-xs font-bold text-muted-ink">Connected Translators</dt><dd className="mt-0.5 line-clamp-2 font-semibold text-ink">{references.map((reference) => reference.translator.name).join(", ") || "None"}</dd></div></dl>
              <div className="mt-4 flex flex-wrap items-center justify-between gap-3">{idea.status === "PUBLISHED" ? <Link href={`/ideas/${idea.slug}`} className="inline-flex items-center gap-1.5 text-sm font-bold text-brand-700 hover:text-brand-900">View public page <ExternalLink className="h-3.5 w-3.5" aria-hidden="true" /></Link> : <span className="text-xs text-muted-ink">Public page unavailable</span>}<time className="text-xs text-muted-ink">Updated {idea.updatedAt.toLocaleDateString()}</time></div>
              {idea.currentVersion ? <div className="mt-4"><IdeaVersionActions ideaId={idea.id} checksum={idea.currentVersion.checksum} archived={idea.status === "ARCHIVED"} versions={idea.versions.filter((version) => version.id !== idea.currentVersionId).map((version) => ({ id: version.id, version: version.version }))} /></div> : null}
              <details className="group mt-4 border-t border-border pt-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-xs font-bold text-muted-ink hover:text-ink"><span>Technical and content audit</span><ChevronDown className="h-4 w-4 transition group-open:rotate-180" aria-hidden="true" /></summary><div className="mt-3 rounded-xl bg-muted-surface p-3 text-xs"><dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-2"><dt className="font-bold">Idea ID</dt><dd className="break-all">{idea.id}</dd><dt className="font-bold">Checksum</dt><dd className="break-all">{idea.currentVersion?.checksum || "None"}</dd><dt className="font-bold">Decision</dt><dd className="break-all">{idea.decisions[0]?.id || "None"}</dd><dt className="font-bold">Opportunity</dt><dd className="break-all">{idea.decisions[0]?.opportunity?.id || "None"}</dd></dl><details className="mt-3"><summary className="cursor-pointer font-bold">Structured blocks and quality JSON</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap text-[11px]">{JSON.stringify({ blocks: idea.currentVersion?.blocks || [], quality: idea.currentVersion?.qualityResult || null }, null, 2)}</pre></details></div></details>
            </div>
          </article>;
        })}</div> : <div className="mt-6 rounded-[1.5rem] border border-dashed border-border p-8 text-center"><h3 className="font-display text-xl font-bold text-ink">No Ideas yet</h3><p className="mt-1 text-sm text-muted-ink">Completed Idea content will appear here.</p></div>}
      </section>

      <section aria-labelledby="recent-decisions-heading" className="border-y border-dashed border-border py-8"><div><p className="section-kicker">Audit trail</p><h2 id="recent-decisions-heading" className="font-display mt-1 text-2xl font-bold text-ink">Recent decisions</h2></div>{overview.decisions.length ? <div className="mt-5 space-y-3">{overview.decisions.map((decision) => <article key={decision.id} className="rounded-2xl border border-border bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-ink">{humanize(decision.type)}</h3><span className={`rounded-lg px-2 py-1 text-[11px] font-extrabold ${statusClass(decision.status)}`}>{humanize(decision.status)}</span></div><p className="mt-1 text-sm text-muted-ink">{decision.opportunity?.cluster?.name || (decision.opportunity ? humanize(decision.opportunity.type) : "No source opportunity")} · {decision.confidence}% confidence</p></div><time className="text-xs text-muted-ink">{decision.createdAt.toLocaleString()}</time></div><details className="group mt-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-xs font-bold text-muted-ink"><span>Full decision audit</span><ChevronDown className="h-4 w-4 transition group-open:rotate-180" aria-hidden="true" /></summary><div className="mt-3 rounded-xl bg-muted-surface p-3 text-xs"><p className="break-all"><strong>Decision:</strong> {decision.id}</p><p className="mt-1 break-all"><strong>Opportunity:</strong> {decision.opportunityId || "None"}</p><p className="mt-1"><strong>Idea:</strong> {decision.idea?.slug || "None"}</p><pre className="mt-3 max-h-64 overflow-auto whitespace-pre-wrap text-[11px]">{JSON.stringify({ reasonCodes: decision.reasonCodes, outcome: decision.actualOutcome }, null, 2)}</pre></div></details></article>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-border p-5 text-sm text-muted-ink">No Idea decisions yet.</p>}</section>

      <section aria-labelledby="taxonomy-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">Reference</p><h2 id="taxonomy-heading" className="font-display mt-1 text-2xl font-bold text-ink">Idea taxonomy</h2></div><span className="text-sm text-muted-ink">{activeCategories} active categories</span></div><div className="mt-4 grid gap-x-6 gap-y-4 sm:grid-cols-2 xl:grid-cols-3">{overview.categories.map((item) => <article key={item.id} className="border-l-2 border-supporting-300 pl-4"><div className="flex items-center gap-2"><h3 className="font-bold text-ink">{item.name}</h3><span className={`text-[10px] font-extrabold uppercase tracking-wider ${item.isActive && !item.archivedAt ? "text-brand-700" : "text-red-700"}`}>{item.isActive && !item.archivedAt ? "Active" : "Unavailable"}</span></div><p className="mt-1 text-sm leading-5 text-muted-ink">{item.description}</p><p className="mt-1 text-xs text-muted-ink">/ideas?category={item.slug}</p></article>)}</div></section>
    </main>
  </>;
}
