import Link from "next/link";

import { IdeaVersionActions, QueueIdeaDecisionButton } from "@/components/admin/idea-autopilot-actions";
import { getAdminIdeasOverview } from "@/lib/data/ideas";
import { requireAdmin } from "@/lib/permissions";

export const dynamic = "force-dynamic";

export default async function AdminGrowthIdeasPage() {
  await requireAdmin();
  const overview = await getAdminIdeasOverview();
  return <div className="space-y-8"><div><p className="text-sm font-bold uppercase tracking-wide text-brand-700">Growth</p><h1 className="font-display mt-1 text-4xl font-bold text-ink">SayTwist Ideas</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-ink">Bounded Idea planning, immutable versions, publication, archive, and rollback. Jobs run only through the one-shot Growth worker.</p></div>
    <section><h2 className="font-display text-2xl font-bold text-ink">Taxonomy</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{overview.categories.map((item) => <article key={item.id} className="rounded-2xl border border-border bg-white p-4"><p className="font-bold text-ink">{item.name}</p><p className="mt-1 text-xs text-muted-ink">/{item.slug} · {item.isActive && !item.archivedAt ? "Active" : "Unavailable"}</p><p className="mt-2 text-sm leading-5 text-muted-ink">{item.description}</p></article>)}</div></section>
    <section><h2 className="font-display text-2xl font-bold text-ink">Eligible opportunities</h2><div className="mt-3 space-y-3">{overview.opportunities.length ? overview.opportunities.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-border bg-white p-4"><div><p className="font-bold text-ink">{item.cluster?.name || item.type}</p><p className="text-xs text-muted-ink">{item.type} · score {item.score} · confidence {item.confidence}% · {item.evidenceQuality}</p></div><QueueIdeaDecisionButton opportunityId={item.id} /></article>) : <p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted-ink">No open opportunities.</p>}</div></section>
    <section><h2 className="font-display text-2xl font-bold text-ink">Recent decisions</h2><div className="mt-3 space-y-3">{overview.decisions.length ? overview.decisions.map((decision) => <article key={decision.id} className="rounded-2xl border border-border bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold text-ink">{decision.type} · {decision.status}</p><p className="mt-1 text-xs text-muted-ink">{decision.opportunity?.cluster?.name || decision.opportunity?.type || "No source opportunity"} · confidence {decision.confidence}%</p></div><p className="text-xs text-muted-ink">{decision.createdAt.toLocaleString()}</p></div><p className="mt-2 break-all text-xs text-muted-ink">Decision {decision.id} · Opportunity {decision.opportunityId || "none"} · Idea {decision.idea?.slug || "none"}</p><details className="mt-3"><summary className="cursor-pointer text-sm font-bold text-ink">Inspect reasons and outcome</summary><pre className="mt-2 max-h-64 overflow-auto rounded-xl bg-muted-surface p-3 text-xs">{JSON.stringify({ reasonCodes: decision.reasonCodes, outcome: decision.actualOutcome }, null, 2)}</pre></details></article>) : <p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted-ink">No Idea decisions yet.</p>}</div></section>
    <section><h2 className="font-display text-2xl font-bold text-ink">Recent Ideas</h2><div className="mt-3 space-y-4">{overview.ideas.length ? overview.ideas.map((idea) => <article key={idea.id} className="rounded-2xl border border-border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-brand-700">{idea.category.name}</p><h3 className="font-display mt-1 text-xl font-bold text-ink">{idea.currentVersion?.title || idea.slug}</h3><p className="mt-1 text-xs text-muted-ink">{idea.status} · v{idea.currentVersion?.version || 0} · {idea.currentVersion?.checksum || "No checksum"}</p><p className="mt-1 text-xs text-muted-ink">Created {idea.createdAt.toLocaleString()} · Published {idea.publishedAt?.toLocaleString() || "not published"}</p><p className="mt-1 text-xs text-muted-ink">Source decision {idea.decisions[0]?.id || "none"} · opportunity {idea.decisions[0]?.opportunity?.id || "none"}</p><p className="mt-1 text-xs text-muted-ink">Translators: {idea.currentVersion?.translatorReferences.map((reference) => reference.translator.name).join(", ") || "none"}</p></div>{idea.status === "PUBLISHED" ? <Link href={`/ideas/${idea.slug}`} className="text-sm font-bold text-brand-700">View public page</Link> : null}</div>{idea.currentVersion ? <div className="mt-4"><IdeaVersionActions ideaId={idea.id} checksum={idea.currentVersion.checksum} archived={idea.status === "ARCHIVED"} versions={idea.versions.filter((version) => version.id !== idea.currentVersionId).map((version) => ({ id: version.id, version: version.version }))} /></div> : null}<details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-ink">Inspect structured version and quality</summary><pre className="mt-2 max-h-80 overflow-auto rounded-xl bg-muted-surface p-3 text-xs">{JSON.stringify({ blocks: idea.currentVersion?.blocks || [], quality: idea.currentVersion?.qualityResult || null }, null, 2)}</pre></details></article>) : <p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted-ink">No Ideas yet.</p>}</div></section>
  </div>;
}
