export const TRANSLATOR_AUTOPILOT_VERSION = "translator_autopilot_v1";
export const TRANSLATOR_QUALITY_VERSION = "translator_quality_v1";
export const TRANSLATOR_DEDUPE_VERSION = "translator_dedupe_v1";
export const TRANSLATOR_SNAPSHOT_VERSION = "translator_snapshot_v1";

export const MAX_TRANSLATOR_SNAPSHOT_BYTES = 64 * 1024;
export const MAX_GENERATION_BRIEF_BYTES = 24 * 1024;
export const MAX_CATEGORY_OPTIONS = 40;
export const MAX_RELATED_TRANSLATORS = 40;
export const MAX_REPRESENTATIVE_PINS = 12;
export const MAX_DEDUPE_CANDIDATES = 500;

export const CREATE_SCORE_MIN = 75;
export const CREATE_CONFIDENCE_MIN = 80;
export const IMPROVE_SCORE_MIN = 70;
export const IMPROVE_CONFIDENCE_MIN = 75;

export const DECISION_REASON = {
  ACTIONABLE_CREATE: "ACTIONABLE_CREATE",
  ACTIONABLE_IMPROVE: "ACTIONABLE_IMPROVE",
  AMPLIFY_REQUIRES_EXISTING_TARGET: "AMPLIFY_REQUIRES_EXISTING_TARGET",
  CATEGORY_AMBIGUOUS: "CATEGORY_AMBIGUOUS",
  CATEGORY_UNAVAILABLE: "CATEGORY_UNAVAILABLE",
  DUPLICATE_CREATE_BLOCKED: "DUPLICATE_CREATE_BLOCKED",
  DEDUPE_CORPUS_TRUNCATED: "DEDUPE_CORPUS_TRUNCATED",
  CREATE_SLUG_COLLISION: "CREATE_SLUG_COLLISION",
  GROWTH_DISABLED_BEFORE_APPLY: "GROWTH_DISABLED_BEFORE_APPLY",
  SOURCE_OPPORTUNITY_CHANGED: "SOURCE_OPPORTUNITY_CHANGED",
  DECISION_NOT_EXECUTABLE: "DECISION_NOT_EXECUTABLE",
  CATEGORY_CHANGED_BEFORE_APPLY: "CATEGORY_CHANGED_BEFORE_APPLY",
  EVIDENCE_NOT_KNOWN: "EVIDENCE_NOT_KNOWN",
  FATIGUE_REQUIRES_CLEAR_TARGET: "FATIGUE_REQUIRES_CLEAR_TARGET",
  GENERIC_TOPIC_INSUFFICIENT: "GENERIC_TOPIC_INSUFFICIENT",
  MULTIPLE_TARGETS_AMBIGUOUS: "MULTIPLE_TARGETS_AMBIGUOUS",
  NO_MATERIAL_IMPROVEMENT: "NO_MATERIAL_IMPROVEMENT",
  OPPORTUNITY_NOT_OPEN: "OPPORTUNITY_NOT_OPEN",
  SCORE_OR_CONFIDENCE_LOW: "SCORE_OR_CONFIDENCE_LOW",
  TARGET_ALREADY_COMPLETE: "TARGET_ALREADY_COMPLETE",
  TARGET_CHANGED: "TARGET_CHANGED",
} as const;
