export const IDEA_AUTOPILOT_VERSION = "idea_autopilot_v1";
export const IDEA_GENERATION_VERSION = "idea_generation_v1";
export const IDEA_QUALITY_VERSION = "idea_quality_v1";
export const IDEA_DEDUPE_VERSION = "idea_dedupe_v1";
export const IDEA_SNAPSHOT_VERSION = "idea_snapshot_v1";

export const MAX_IDEA_VERSION_BYTES = 96 * 1024;
export const MAX_IDEA_GENERATION_BRIEF_BYTES = 32 * 1024;
export const MAX_IDEA_BLOCKS = 32;
export const MAX_IDEA_LIST_ITEMS = 40;
export const MAX_IDEA_DEDUPE_CANDIDATES = 500;
export const MAX_IDEA_REPRESENTATIVE_PINS = 12;
export const MAX_IDEA_RELATED_TRANSLATORS = 40;
export const MAX_EXISTING_IDEAS_IN_BRIEF = 40;

export const IDEA_CREATE_SCORE_MIN = 70;
export const IDEA_CREATE_CONFIDENCE_MIN = 75;
export const IDEA_IMPROVE_SCORE_MIN = 65;
export const IDEA_IMPROVE_CONFIDENCE_MIN = 70;

export const IDEA_DECISION_REASON = {
  ACTIONABLE_CREATE: "ACTIONABLE_CREATE_IDEA",
  ACTIONABLE_IMPROVE: "ACTIONABLE_IMPROVE_IDEA",
  ALREADY_WELL_COVERED: "IDEA_ALREADY_WELL_COVERED",
  CATEGORY_CHANGED: "IDEA_CATEGORY_CHANGED_BEFORE_APPLY",
  CATEGORY_UNAVAILABLE: "IDEA_CATEGORY_UNAVAILABLE",
  DEDUPE_CAP_EXCEEDED: "IDEA_DEDUPE_CAP_EXCEEDED",
  DUPLICATE_BLOCKED: "IDEA_DUPLICATE_BLOCKED",
  EVIDENCE_NOT_KNOWN: "IDEA_EVIDENCE_NOT_KNOWN",
  FATIGUE_REQUIRES_TARGET: "IDEA_FATIGUE_REQUIRES_TARGET",
  GENERIC_TOPIC_INSUFFICIENT: "IDEA_GENERIC_TOPIC_INSUFFICIENT",
  GROWTH_DISABLED_BEFORE_APPLY: "GROWTH_DISABLED_BEFORE_IDEA_APPLY",
  MULTIPLE_IDEAS_AMBIGUOUS: "MULTIPLE_IDEAS_AMBIGUOUS",
  NO_MATERIAL_IMPROVEMENT: "NO_MATERIAL_IDEA_IMPROVEMENT",
  OPPORTUNITY_NOT_OPEN: "IDEA_OPPORTUNITY_NOT_OPEN",
  SCORE_OR_CONFIDENCE_LOW: "IDEA_SCORE_OR_CONFIDENCE_LOW",
  SOURCE_MODEL_OUTDATED: "IDEA_SOURCE_MODEL_OUTDATED",
  SOURCE_OPPORTUNITY_CHANGED: "IDEA_SOURCE_OPPORTUNITY_CHANGED",
  TARGET_CHANGED: "IDEA_TARGET_CHANGED",
  TRANSLATOR_REFERENCE_CHANGED: "IDEA_TRANSLATOR_REFERENCE_CHANGED",
} as const;
